// src/pages/log-viewer/index.tsx
import { ChevronDown, ChevronRight, Clock3, FileJson, FileUp, Link, Trash2, Upload } from 'lucide-react'
import { useEffect, useMemo, useRef, useState, type DragEvent } from 'react'
import { JsonTree, type JsonTreeController } from '@/components/json-tree/JsonTree'
import { Button } from '@/components/ui/button'
import { Tooltip } from '@/components/ui/tooltip'
import { pathKey } from '@/lib/jsonc'
import { getActiveLog, getLogs, useLogViewerStore } from '@/stores/log-viewer'

function PayloadTree({ value }: { value: unknown }) {
  const [expandMap, setExpandMap] = useState<Map<string, boolean>>(() => new Map())
  const emptyMatches = useMemo(() => new Set<string>(), [])
  useEffect(() => setExpandMap(new Map()), [value])
  const controller = useMemo<JsonTreeController>(() => ({
    indentSize: '2',
    sortMode: 'asc',
    query: '',
    matchedPathKeys: emptyMatches,
    currentMatchKey: null,
    isExpanded: (segments) => expandMap.get(pathKey(segments)) ?? true,
    setExpanded: (segments, expanded) => setExpandMap((current) => new Map(current).set(pathKey(segments), expanded)),
    toggleExpanded: (segments) => setExpandMap((current) => {
      const next = new Map(current)
      const key = pathKey(segments)
      next.set(key, !(next.get(key) ?? true))
      return next
    }),
  }), [expandMap, emptyMatches])
  return <div className="min-h-0 flex-1 overflow-auto p-3"><JsonTree value={value} hasValue controller={controller} /></div>
}

function LogTabBar({ importFiles }: { importFiles: (files: File[]) => Promise<void> }) {
  const { groups, activeId, setActive, clearLogs } = useLogViewerStore()
  const [collapsedGroupIds, setCollapsedGroupIds] = useState<Set<string>>(() => new Set())
  const fileInput = useRef<HTMLInputElement>(null)
  const logs = getLogs(groups)
  const isExpanded = (id: string) => !collapsedGroupIds.has(id)
  const toggleGroup = (id: string) => setCollapsedGroupIds((current) => {
    const next = new Set(current)
    if (next.has(id)) next.delete(id)
    else next.add(id)
    return next
  })

  return (
    <aside className="flex h-full w-28 shrink-0 flex-col border-r bg-muted/30 p-2 sm:w-44" aria-label="请求日志">
      <div className="mb-2 flex h-8 items-center px-2"><span className="text-xs font-medium text-muted-foreground">请求日志</span><span className="ml-auto font-mono text-[11px] text-muted-foreground">{logs.length}</span></div>
      <div className="min-h-0 flex-1 space-y-3 overflow-y-auto">
        {groups.map((group) => (
          <section key={group.id} aria-label={group.name}>
            <button type="button" className="flex h-7 w-full min-w-0 items-center gap-1.5 rounded-sm px-2 text-left text-[11px] text-muted-foreground hover:bg-background/60 hover:text-foreground" aria-expanded={isExpanded(group.id)} aria-label={`${isExpanded(group.id) ? '收起' : '展开'} ${group.name}`} title={group.name} onClick={() => toggleGroup(group.id)}>{isExpanded(group.id) ? <ChevronDown size={12} /> : <ChevronRight size={12} />}<FileJson size={14} /><span className="min-w-0 flex-1 truncate">{group.name}</span><span className="font-mono">{group.logs.length}</span></button>
            {isExpanded(group.id) && <div className="space-y-1">{group.logs.map((log) => <button key={log.id} type="button" className={`flex h-9 w-full items-center rounded-md px-2 text-left text-xs ${activeId === log.id ? 'bg-background text-foreground shadow-xs' : 'text-muted-foreground hover:bg-background/60 hover:text-foreground'}`} aria-current={activeId === log.id ? 'page' : undefined} title={log.url} onClick={() => setActive(log.id)}><span className="truncate">{log.name}</span></button>)}</div>}
          </section>
        ))}
        {!logs.length && <p className="px-2 py-4 text-xs leading-5 text-muted-foreground">暂无日志</p>}
      </div>
      <div className="mt-2 flex items-center gap-1 border-t pt-2">
        <Tooltip content="导入日志文件"><Button type="button" variant="ghost" size="icon" aria-label="导入日志文件" onClick={() => fileInput.current?.click()}><FileUp size={16} /></Button></Tooltip>
        <Tooltip content="清空日志"><Button type="button" variant="ghost" size="icon" aria-label="清空日志" disabled={!logs.length} onClick={clearLogs}><Trash2 size={16} /></Button></Tooltip>
        <input ref={fileInput} className="hidden" type="file" accept="application/json,.json,.log.json" multiple onChange={(event) => { const files = Array.from(event.target.files ?? []); event.target.value = ''; if (files.length) void importFiles(files) }} />
      </div>
    </aside>
  )
}

export function LogViewerPage() {
  const { groups, activeId, addLogGroup } = useLogViewerStore()
  const activeLog = getActiveLog(groups, activeId)
  const [isDraggingFiles, setIsDraggingFiles] = useState(false)
  const [notice, setNotice] = useState<string | null>(null)
  const importFiles = async (files: File[]) => {
    let importedCount = 0
    const failures: string[] = []
    for (const file of files) {
      try {
        addLogGroup(file.name, JSON.parse(await file.text()) as unknown)
        importedCount++
      } catch (error) {
        failures.push(`${file.name}: ${error instanceof Error ? error.message : '文件内容无效'}`)
      }
    }
    const total = getLogs(useLogViewerStore.getState().groups).length
    setNotice(failures.length ? `${importedCount ? `已导入 ${importedCount} 个文件。` : ''}${failures.join('；')}` : `已导入 ${importedCount} 个文件，共 ${total} 条请求`)
  }
  const containsFiles = (event: DragEvent) => Array.from(event.dataTransfer.types).includes('Files')
  const duration = activeLog?.duration === undefined || activeLog?.duration === '' ? '耗时未知' : String(activeLog.duration)
  const requestTime = activeLog?.reqTime === undefined || activeLog?.reqTime === '' ? null : String(activeLog.reqTime)

  return (
    <main className="relative flex min-h-0 flex-1" onDragEnter={(event) => { event.preventDefault(); if (containsFiles(event)) setIsDraggingFiles(true) }} onDragOver={(event) => event.preventDefault()} onDragLeave={(event) => { if (event.currentTarget === event.target) setIsDraggingFiles(false) }} onDrop={(event) => { event.preventDefault(); setIsDraggingFiles(false); void importFiles(Array.from(event.dataTransfer.files)) }}>
      <LogTabBar importFiles={importFiles} />
      <section className="flex min-w-0 flex-1 flex-col">
        {notice && <div className="flex items-center justify-between border-b bg-secondary px-3 py-2 text-xs"><span>{notice}</span><Button type="button" variant="ghost" size="sm" className="text-muted-foreground" aria-label="关闭提示" onClick={() => setNotice(null)}>关闭</Button></div>}
        {activeLog ? <>
          <header className="flex min-h-14 shrink-0 flex-wrap items-center gap-x-4 gap-y-2 border-b px-4 py-2"><div className="flex min-w-0 flex-1 items-center gap-2"><Link className="shrink-0 text-muted-foreground" size={16} /><span className="truncate font-mono text-sm" title={activeLog.url}>{activeLog.url}</span></div><span className="flex shrink-0 items-center gap-1.5 text-xs text-muted-foreground"><Clock3 size={14} />请求耗时 {duration}</span>{requestTime && <span className="flex shrink-0 items-center gap-1.5 text-xs text-muted-foreground"><Clock3 size={14} />请求时间 {requestTime}</span>}</header>
          <div className="grid min-h-0 flex-1 grid-cols-1 lg:grid-cols-2"><section data-log-payload="request" className="flex min-h-0 flex-col border-b lg:border-r lg:border-b-0"><div className="shrink-0 border-b px-3 py-2 text-xs font-medium">请求参数</div><PayloadTree value={activeLog.req ?? null} /></section><section data-log-payload="response" className="flex min-h-0 flex-col"><div className="shrink-0 border-b px-3 py-2 text-xs font-medium">响应参数</div><PayloadTree value={activeLog.res ?? null} /></section></div>
        </> : <div className="flex min-h-0 flex-1 items-center justify-center text-sm text-muted-foreground">导入日志文件后查看请求详情</div>}
      </section>
      {isDraggingFiles && <div className="absolute inset-0 z-20 flex items-center justify-center border-2 border-dashed border-primary bg-background/90"><div className="flex items-center gap-2 text-sm font-medium"><Upload size={20} />释放以导入日志文件</div></div>}
    </main>
  )
}

// src/components/log-viewer/LogViewer.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { Clock3, Link, Upload } from 'lucide-vue-next'
import LogPayloadViewer from './LogPayloadViewer.vue'
import LogTabBar from './LogTabBar.vue'
import { toast } from '@/components/ui/sonner'
import { useLogViewerStore } from '@/stores/log-viewer'

const store = useLogViewerStore()
const isDraggingFiles = ref(false)

const requestValue = computed(() => {
  const log = store.activeLog
  return log?.req ?? null
})

const responseValue = computed(() => {
  const log = store.activeLog
  return log?.res ?? null
})

const durationText = computed(() => {
  const duration = store.activeLog?.duration
  return duration === undefined || duration === '' ? '耗时未知' : String(duration)
})

const requestTimeText = computed(() => {
  const reqTime = store.activeLog?.reqTime
  return reqTime === undefined || reqTime === '' ? null : String(reqTime)
})

function containsFiles(event: DragEvent) {
  return Array.from(event.dataTransfer?.types ?? []).includes('Files')
}

function onDragEnter(event: DragEvent) {
  if (containsFiles(event)) isDraggingFiles.value = true
}

function onDragLeave(event: DragEvent) {
  if (event.currentTarget === event.target) isDraggingFiles.value = false
}

async function importFiles(files: File[]) {
  let importedCount = 0
  const failures: string[] = []

  for (const file of files) {
    try {
      store.addLogGroup(file.name, JSON.parse(await file.text()) as unknown)
      importedCount++
    } catch (error) {
      const detail = error instanceof Error ? error.message : '文件内容无效'
      failures.push(`${file.name}：${detail}`)
    }
  }

  if (importedCount) {
    const successToastOptions = {
      title: '日志已导入',
      description: `已导入 ${importedCount} 个文件，共 ${store.logs.length} 条请求`,
      position: 'top-right' as const,
    }
    toast.success('日志已导入', successToastOptions)
  }
  if (failures.length) {
    toast.error('部分日志未导入', {
      description: failures.join('；'),
      position: 'top-right',
    })
  }
}

function onDrop(event: DragEvent) {
  isDraggingFiles.value = false
  void importFiles(Array.from(event.dataTransfer?.files ?? []))
}
</script>

<template>
  <div
    class="relative flex h-full min-h-0"
    @dragenter.prevent="onDragEnter"
    @dragover.prevent
    @dragleave="onDragLeave"
    @drop.prevent="onDrop"
  >
    <LogTabBar @import="importFiles" />

    <section class="flex min-w-0 flex-1 flex-col">
      <template v-if="store.activeLog">
        <header class="flex min-h-14 shrink-0 flex-wrap items-center gap-x-4 gap-y-2 border-b px-4 py-2">
          <div class="flex min-w-0 flex-1 items-center gap-2">
            <Link class="size-4 shrink-0 text-muted-foreground" />
            <span class="truncate font-mono text-sm" :title="store.activeLog.url">
              {{ store.activeLog.url }}
            </span>
          </div>

          <span class="flex shrink-0 items-center gap-1.5 text-xs text-muted-foreground">
            <Clock3 class="size-3.5" /> 请求耗时 {{ durationText }}
          </span>
          <span
            v-if="requestTimeText"
            class="flex shrink-0 items-center gap-1.5 text-xs text-muted-foreground"
          >
            <Clock3 class="size-3.5" /> 请求时间 {{ requestTimeText }}
          </span>
        </header>

        <div class="grid min-h-0 flex-1 grid-cols-1 lg:grid-cols-2">
          <section data-log-payload="request" class="flex min-h-0 flex-col border-b lg:border-r lg:border-b-0">
            <div class="shrink-0 border-b px-3 py-2 text-xs font-medium">请求参数</div>
            <LogPayloadViewer :value="requestValue" />
          </section>
          <section data-log-payload="response" class="flex min-h-0 flex-col">
            <div class="shrink-0 border-b px-3 py-2 text-xs font-medium">响应参数</div>
            <LogPayloadViewer :value="responseValue" />
          </section>
        </div>
      </template>

      <div v-else class="flex min-h-0 flex-1 items-center justify-center text-sm text-muted-foreground">
        导入日志文件后查看请求详情
      </div>
    </section>

    <div
      v-if="isDraggingFiles"
      class="absolute inset-0 z-20 flex items-center justify-center border-2 border-primary border-dashed bg-background/90"
    >
      <div class="flex items-center gap-2 text-sm font-medium">
        <Upload class="size-5" /> 释放以导入日志文件
      </div>
    </div>
  </div>
</template>
